### ISSUE TITLE
Choose language and platform for create app

### ISSUE THREAD

**Issue by binhleo** [binhleo/chat-app-with-firebase#2]

**Comment by binhleo** [comment]
- Về platform bỏ qua ứng dụng desktop, vì firebase chủ yếu tập trung xây dựng cho 3 nền tảng chính là android, iOS và web
- Vì là ứng dụng chat nên điều cần thiết sẽ là tính tiện dụng, vậy nên sẽ dễ dàng hơn với mobile

**Comment by HoangHung1995** [comment]
Ngôn ngữ chính sẽ là tiếng anh , vì nó thông dụng với mọi người

**Comment by ntmFury** [comment]
gì mà ngôn ngữ tiếng anh ở đây :V chọn ngôn ngữ lập trình chứ

**Comment by binhleo** [comment]
Nếu có thể t muốn app của mình có thể xây dựng đc trên cả 3 nền tảng là web, android và ios. T sẽ cố dùng cocos2d-x để làm app android xem thế nào@@

**Comment by binhleo** [comment]
Web chat có link để có thể tải app trên android và ios

**Comment by HoangHung1995** [comment]
Tôi nghĩ tập trung xây dựng trên nền tảng Android và IOS
