### ISSUE TITLE
Merely sending text messages or sending more with pictures, sounds, emotion, ...

### ISSUE THREAD

**Issue by binhleo** [binhleo/chat-app-with-firebase#4]

**Comment by HoangHung1995** [comment]
Gửi tin nhắn ngoài văn bản ra , có thêm icon , hình ảnh hoặc biểu tượng cảm xúc sẽ làm cuộc trò chuyện không bị nhàm chán , trở nên thú vị hơn , giúp bạn có thể bộc lộ cảm xúc thông qua hình ảnh , icon thay vì text sẽ buồn chán hơn rất nhiều

**Comment by HoangHung1995** [comment]
Đôi khi sử dụng icon , hình ảnh , hoặc biểu tượng cảm xúc có thể tiết kiệm thời gian cho người chát
