### ISSUE TITLE
All of user can chat together (public) or only one or some user have relate to each other (room chat)

### ISSUE THREAD

**Issue by binhleo** [binhleo/chat-app-with-firebase#5]

**Comment by HoangHung1995** [comment]
Mình nghĩ tất cả người dùng đều có thể chát cùng nhau , không nhất thiết phải phân quyền cho 1 người

**Comment by ntmFury** [comment]
Tất cả mọi người ở đây là như nào? Là tất cả những người vào đăng kí tk có thể chat với nhau trên 1 khung chat à ?

**Comment by HoangHung1995** [comment]
Đúng vậy . quyền chát của mọi người như nhau

**Comment by HoangHung1995** [comment]
chứ không phải người tạo ra khung chát thì có quyền chát với những người khác

**Comment by binhleo** [comment]
nghĩa là mình chỉ có 1 phòng chat, tất cả mn có thể thấy được message của nhau

**Comment by ntmFury** [comment]
những tài khoản đăng nhập trên app là cố định như kiểu fb thì tên ko được thay đổi khi chat với nhau  , hay mỗi khi đăng nhập vào app  mình lại lấy 1 tên mà mình thích rồi chat thôi  như : https://chatbox-23d3c.firebaseapp.com/  thôi

**Comment by binhleo** [comment]
mỗi người khi truy cập vào app đều sẽ phải có 1 tài khoản với username nhất định, mặc định sẽ là không thay đổi đc!! @@

**Comment by ntmFury** [comment]
tức là đến lần truy cập sau thì vẫn phải  là tk và username đó ?
không đc nhắn tin theo kiểu nặc danh :)) không cho người khác biết người nhắn lần sau này có phải là người lần trước ko :))

**Comment by binhleo** [comment]
đúng dồi đấy!! 👍

**Comment by ntmFury** [comment]
Theo t thì mình sẽ làm 1 form đăng nhập đơn giản cho người dùng nhập nickname kiểu như này: https://chatbox-23d3c.firebaseapp.com/  (nickname ko cần cố định mỗi lần vào có thể lấy 1 tên khác nhau không cần tk mk gì cả cho rắc rối  ) sau khi vào sẽ hiển thị các list phòng chat theo chủ đề vd: 
1. Phòng chat tìm bạn tình :D  : những người cần kết bạn tìm bạn trai bạn gái chẳng hạn mọi người vào đó có thể xin infor của nhau để làm quen
2.Phòng tán gẫu chém gió
3. Phòng tâm sự tuổi teen  :))) 
4. Phòng 18+-*/ : có tin nhắn tự xóa :v 
...............................................................
tất cả những người sử dụng ứng dụng(website) đều có thể vào các phòng nt đc với nhau, tùy  theo nhu cầu của từng người để chọn các phòng chat theo các chủ đề họ quan tâm
Chứ ko phải làm kiểu như : 1 người phải tạo tk mk cố định , rồi kết bạn tạo phòng chat mời người này người kia vào 
Theo t thì như thế :D

**Comment by binhleo** [comment]
về phòng chat thì chắc chắn sẽ có.. nhưng t vẫn muốn mỗi người có 1 tk truy cập riêng để có thể liên hệ với nhau. Vì nếu chỉ dùng phòng chat thì app của mình chắc chắn sẽ không đc phổ biến
Phòng chat nên là một chức năng.. tương tự QQ

**Comment by HoangHung1995** [comment]
Thế ví dụ người dùng muốn thay đổi tài khoản hay là password thì có thể thay đổi được không ?
