### ISSUE TITLE
Consider adding additional the message is automatically deleted 

### ISSUE THREAD

**Issue by ntmFury** [binhleo/chat-app-with-firebase#6]

**Comment by binhleo** [comment]
Tin nhắn sẽ bị xóa sau khoảng thời gian tính từ mốc lúc gửi đi hay mốc lúc người nhận xem tin nhắn!! @@

**Comment by ntmFury** [comment]
mốc tính từ lúc mình gửi đi,  vd sau 1 khoảng thời gian 30s sau khi gửi tin nhắn đi tn sẽ tự động xóa để đảm bảo tính bảo mật ko nhỡ có người đọc đc tin nhắn của mình

**Comment by binhleo** [comment]
cái này còn tùy vào việc lựa chọn phương thức chat thế nào

**Comment by binhleo** [comment]
nếu chat là riêng tư thì nhỡ sau 30s người nhận vẫn chưa đọc thì tin nhắn này nếu như quan trọng sẽ không đến đc tay người nhận

**Comment by ntmFury** [comment]
bài toán là làm sao để biết người nhận đã đọc tin nhắn hay chưa ?

**Comment by binhleo** [comment]
cái đấy sẽ cần phải google chứ.. tôi cũng là tìm hiểu đâu!!

**Comment by ntmFury** [comment]
t nghĩ là khó đấy :D tốt nhất là cứ sau 1 khoảng thời gian nhất gửi tn đi thì sẽ tự bị xóa

**Comment by binhleo** [comment]
chắc fb có API hỗ trợ!!

**Comment by HuongSen** [comment]
ơ thế người nhận phải đọc đc sau 1-2p nó mới tự động xóa chứ

**Comment by vuongthuyanh** [comment]
t nghĩ việc xóa hay không phần tin nhắn đã đc gửi thi nên để tùy chọn theo ý ngươi dùng, chứ nếu xóa hết đi người ta muốn xem lại lịch sử chat thì sao?

**Comment by binhleo** [comment]
Nếu tùy ý người dùng sẽ không thú vị.. vì ai chẳng muốn xem lại lịch sử chat

**Comment by binhleo** [comment]
Firebase sẽ tự nhận biết khi nào người dùng xem tn.. vì thế mình sẽ xóa tn ngay khi người nhận đọc sau 1 phút

**Comment by vuongthuyanh** [comment]
Ứng dụng chat mà lại chỉ chờ ng đọc đc rồi xóa đi, như vậy thì giả sử như gửi tệp, ng dùng đọc xong chưa kịp tải cũng bị xóa. Hay như chat nhiều ng, trong đó có 1 ng đọc đc cái là xóa ngay ???, t thấy cái kiểu chat xong tự động xóa luôn nên là một chức năng tùy chọn của ng dùng thì sẽ tốt hơn chứ

**Comment by HangNguyen12** [comment]
sau 1 thời gian khi người nhân nhận được rồi bị xóa đi thì nhuoc điêm quá

**Comment by HoangHung1995** [comment]
Sau 1 thời gian mà người đọc chưa xem thì tin nhắn tự động bị xóa đi sao

**Comment by HoangHung1995** [comment]
Như vậy người dùng muốn xem lịch sử chát thì không thể xem được rồi
